
# Credential Rotation Demo  10/1 rotated credential
# Runner hosted on cphost  run bash actions-runner/run.sh

name: Fetch Secrets from Conjur

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  fetch-secrets:
    runs-on: self-hosted  # Specify your self-hosted runner label and OS
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: cyberark/conjur-action@v2.0.5
        with:
          url: https://.cloud/api
          account: conjur
          authn_id: [github_dodge_demo]
          secrets: |
            data/vault/dodge_test/Ansible-DBA-MySQL/password;
      
      - run: |
          echo $CONJUR_PASS | sed 's/./& /g'
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN
